apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Worker assíncrono gerado pelo Golden Path worker-event
  tags:
    - nodejs
    - typescript
    - worker
    - events
    - golden-path
  annotations:
    github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: idp-platform
