SHELL := /usr/bin/env bash

.PHONY: install dev lint test build start

install:
	corepack enable && yarn install

dev:
	yarn dev

lint:
	yarn lint

test:
	yarn test

build:
	yarn build

start:
	yarn start
