apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservice-http
  title: Golden Path - Microservice HTTP
  description: Cria um serviço HTTP Node.js/TypeScript com padrões de observabilidade e saúde.
  tags:
    - golden-path
    - http
    - nodejs
spec:
  owner: group:default/platform-team
  type: service
  parameters:
    - title: Metadados do Serviço
      required:
        - name
        - owner
        - repoUrl
      properties:
        name:
          title: Nome do serviço
          type: string
          pattern: '^[a-z0-9-]+$'
          description: Nome técnico do serviço (kebab-case)
        owner:
          title: Owner
          type: string
          default: group:default/platform-team
          description: Entidade de owner no Backstage
        repoUrl:
          title: Repositório Git
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch-base
      name: Baixar skeleton
      action: fetch:template
      input:
        url: https://github.com/saviocodess/goldenpath-idp/tree/main/templates/microservice-http/skeleton
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          repo_owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo_name: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

    - id: publish
      name: Publicar repositório
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        description: Serviço HTTP criado pelo Golden Path IDP

    - id: register
      name: Registrar no catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repositório
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Catálogo Backstage
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
