apiVersion: v1
kind: Secret
metadata:
  name: goldenpath-idp-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/saviocodess/goldenpath-idp.git
